### ISSUE TITLE
Todo: make more states

### ISSUE THREAD

**Issue by RyosukeCla** [RyosukeCla/skelt#1]
- [x] remove file or dir with option
- [ ] easy insert new line
- [x] batch execute
- [x] case conversions (Camel Case, Snake Case, Kebab Case)
